#Import variables
Import('env install_prefix staticObjs sharedObjs headers')

sources = [ 'fibheap.c',
            'vertex.cc',
            'edge.cc',
            'graph.cc',
            'cost.cc',
            'search.cc',
            'gridcost.cc',
            'gridsearch.cc'
            ]
                               
headers.append( [  
                '#lib/fibheap.h',
                '#lib/libiberty.h',
                '#lib/ansidecl.h',
                '#lib/vertex.h',
                '#lib/edge.h',
                '#lib/graph.h',
                '#lib/cost.h',                
                '#lib/search.h',
                '#lib/gridcost.h',
                '#lib/gridsearch.h'
                ])

staticObjs.append( env.StaticObject(sources) )
sharedObjs.append( env.SharedObject(sources) )
