D*Lite: dsl::Cost Class Reference
dsl::Cost Class Reference
#include <cost.h>
Public Member Functions
virtual double Heur (const Vertex &va, const Vertex &vb) const =0
virtual double Real (const Vertex &va, const Vertex &vb) const
Detailed Description
Interface defining the cost b/n two vertices. Graph search algorithms often require two types of cost:
* the best possible real cost that a path b/n two vertices can have
* a heuristic cost that is an underestimate of that real cost but is useful during path searching.
This interface defines the two types of costs. The heuristic function is more important and subclasses of this interface are required to provide it. The real function is used only for tie-breaking and is not crucial but could change performance in certain cases.
Author: Marin Kobilarov -- Copyright (C) 2004
Member Function Documentation
virtual double dsl::Cost::Heur (const Vertex & va, const Vertex & vb) const [pure virtual]
Heuristic distance (should be admissible, i.e. less than the real minimum distance) b/n two vertices. Subclasses must provide this function
Parameters:
va first vertex
vb second vertex
Returns:
heuristic distance (optimal cost)
Implemented in dsl::GridCost, and dsl::GridCost3D.
Referenced by dsl::Search::CalculateExtKey(), dsl::Search::Plan(), Real(), and dsl::Search::SetGoal().
double Cost::Real (const Vertex & va, const Vertex & vb) const [virtual]
Real best possible distance b/n two vertices. Subclasses should optionally provide this function. By default it is the heuristic function + epsilon
Parameters:
va first vertex
vb second vertex
Returns:
real minimum possible cost b/n va and vb
Reimplemented in dsl::GridCost, and dsl::GridCost3D.
References Heur().
Referenced by dsl::Search::MinSucc().
The documentation for this class was generated from the following files:
/home/matt/dsl/lib/cost.h
/home/matt/dsl/lib/cost.cc