D*Lite: dsl::GridSearch Class Reference
dsl::GridSearch Class Reference
#include <gridsearch.h>
Public Member Functions
GridSearch (int width, int height, const double *map=0, double scale=1.0, bool setup_edges=true)
virtual ~GridSearch ()
void SetCost (int x, int y, double cost)
double GetCost (int x, int y) const
void SetMap (const double *map)
void SetStart (int x, int y)
void SetGoal (int x, int y)
void Plan (GridPath &path)
void OptPath (const GridPath &path, GridPath &optPath) const
Vertex * GetVertex (int x, int y) const
void RemoveVertex (int x, int y)
void AddEdge (int x1, int y1, int x2, int y2)
virtual double CalcEdgeCost (double v1cost, double v2cost, double elength)
Public Attributes
int width
width of cost grid
int height
height of cost grid
double scale
scale of each cell cost and each transition cost
double * map
cost grid array of size width*height
Protected Attributes
Graph graph
graph
GridCost cost
cost interface
Vertex ** vertexMap
vertex grid array of size width*height
Static Protected Attributes
static const int NBR_OFFSETS [8 *2] = {-1,-1, 0,-1, 1,-1, -1,0, 1,0, -1,1, 0,1 ,1,1}
static const double NBR_COSTS_ [8] = {SQRT2, 1.0, SQRT2, 1.0, 1.0, SQRT2, 1.0, SQRT2}
Constructor & Destructor Documentation
GridSearch::GridSearch (int width, int height, const double * map = 0, double scale = 1.0, bool setup_edges = true)
The planner allocates all states in the beginning a valid map of size width*height should be provided scale is used to multiply each cell value and each neighbor transition value before they are used for planning
Parameters:
width width
height height
map a double array of size width*height containing occupancy info (optional)
scale the size of each cell (default is 1.0)
References dsl::Graph::AddEdge(), dsl::Graph::AddVertex(), CalcEdgeCost(), graph, height, NBR_COSTS_, NBR_COUNT, NBR_OFFSETS, vertexMap, and width.
GridSearch::~GridSearch () [virtual]
References dsl::Vertex::data, height, map, vertexMap, and width.
Member Function Documentation
void GridSearch::AddEdge (int x1, int y1, int x2, int y2)
Useful method for adding edges b/n vertices
Parameters:
x1 from x-coordiante
y1 from y-coordiante
x2 to x-coordiante
y2 to y-coordiante
References dsl::Graph::AddEdge(), GetVertex(), and graph.
double GridSearch::CalcEdgeCost (double v1cost, double v2cost, double elength) [virtual]
Calculates an augmented edge cost as a function of two vertex costs and the original edge cost param v1cost cost of "from" vertex param v2cost cost of "to" vertex param elength 2D distance between vertices
Reimplemented in dsl::TravSearch.
References MAX, and scale.
Referenced by GridSearch(), and SetCost().
double GridSearch::GetCost (int x, int y) const
Get the cost of an individual cell
Parameters:
x x
y y
Returns:
cost
References map, and width.
Referenced by SetCost().
Vertex * GridSearch::GetVertex (int x, int y) const
Useful method to get the graph vertex at position (x,y)
Parameters:
x x-coordiante
y y-coordiante
Returns:
corresponding vertex or 0 if none there
References height, vertexMap, and width.
Referenced by AddEdge(), and RemoveVertex().
void GridSearch::OptPath (const GridPath & path, GridPath & optPath) const
Optimize the path produces by Plan
Parameters:
path an initial obstacle-free path (e.g. one produced by calling Plan(path))
optPath a new path resulting from optimizing the original path path (i.e. a producing a shorter path with minimal number of obstacle-free segments)
References dsl::GridPath::count, dsl::GridPath::len, map, dsl::GridPath::pos, RAY_TRACE_STEP, and width.
Referenced by main().
void GridSearch::Plan (GridPath & path)
Compute path b/n start and goal vertices these vertices should be already set
Parameters:
path the resulting path
References dsl::GridPath::count, dsl::Vertex::data, dsl::GridPath::len, dsl::Vertex::next, dsl::Search::Plan(), dsl::GridPath::pos, and dsl::Search::start.
Referenced by main().
void GridSearch::RemoveVertex (int x, int y)
Useful method to remove a vertex at (x,y)
Parameters:
x x-coordiante
y y-coordiante
References GetVertex(), graph, and dsl::Graph::RemoveVertex().
Referenced by main().
void GridSearch::SetCost (int x, int y, double cost)
Change the cost of an individual cell
Parameters:
x x-coordinate
y y-coordinate
cost cost
References CalcEdgeCost(), dsl::Search::ChangeCost(), cost, dsl::Search::Eq(), GetCost(), dsl::Vertex::in, map, dsl::Vertex::out, vertexMap, and width.
Referenced by main(), and SetMap().
void GridSearch::SetGoal (int x, int y)
Set goal location in the map
Parameters:
x x-coord
y y-coord
References vertexMap, and width.
Referenced by main().
void GridSearch::SetMap (const double * map)
Change the costs of all cells at once
Parameters:
map a width*height double array containing occupancy data
References height, SetCost(), and width.
void GridSearch::SetStart (int x, int y)
Set start location in the map
Parameters:
x x-coord
y y-coord
References vertexMap, and width.
Referenced by main().
Member Data Documentation
GridCost dsl::GridSearch::cost [protected]
cost interface
Reimplemented from dsl::Search.
Referenced by SetCost().
Graph dsl::GridSearch::graph [protected]
graph
Reimplemented from dsl::Search.
Referenced by AddEdge(), GridSearch(), RemoveVertex(), and dsl::TravSearch::TravSearch().
int dsl::GridSearch::height
height of cost grid
Referenced by GetVertex(), GridSearch(), SetMap(), dsl::TravSearch::TravSearch(), and ~GridSearch().
double* dsl::GridSearch::map
cost grid array of size width*height
Referenced by GetCost(), OptPath(), SetCost(), and ~GridSearch().
const double GridSearch::NBR_COSTS_ = {SQRT2, 1.0, SQRT2, 1.0, 1.0, SQRT2, 1.0, SQRT2} [static, protected]
Referenced by GridSearch(), and dsl::TravSearch::TravSearch().
const int GridSearch::NBR_OFFSETS = {-1,-1, 0,-1, 1,-1, -1,0, 1,0, -1,1, 0,1 ,1,1} [static, protected]
Referenced by GridSearch(), and dsl::TravSearch::TravSearch().
double dsl::GridSearch::scale
scale of each cell cost and each transition cost
Referenced by dsl::TravSearch::CalcEdgeCost(), and CalcEdgeCost().
Vertex** dsl::GridSearch::vertexMap [protected]
vertex grid array of size width*height
Referenced by GetVertex(), GridSearch(), SetCost(), SetGoal(), SetStart(), dsl::TravSearch::TravSearch(), and ~GridSearch().
int dsl::GridSearch::width
width of cost grid
Referenced by GetCost(), GetVertex(), GridSearch(), OptPath(), SetCost(), SetGoal(), SetMap(), SetStart(), dsl::TravSearch::TravSearch(), and ~GridSearch().
The documentation for this class was generated from the following files:
/home/matt/dsl/lib/gridsearch.h
/home/matt/dsl/lib/gridsearch.cc