D*Lite: dsl::Search Class Reference
dsl::Search Class Reference
#include <search.h>
Public Member Functions
Search (Graph &graph, const Cost &cost)
virtual ~Search ()
void Reset ()
int Plan ()
void SetStart (const Vertex &v)
void SetGoal (const Vertex &v)
void ChangeCost (Edge &e, double cost)
void SetEps (double eps)
Protected Member Functions
void UpdateVertex (Vertex &u)
void ComputeShortestPath ()
Vertex * MinSucc (double *minRhs, const Vertex &v)
double * CalculateExtKey (double *key, Vertex &v)
double * CalculateKey (Vertex &v)
void Insert (Vertex &v)
void InsertExt (Vertex &v, double *key)
void Update (Vertex &v)
void Remove (Vertex &v)
Vertex * Pop ()
Vertex * Top ()
double * TopKey ()
bool Eq (double a, double b) const
Protected Attributes
Graph & graph
graph
const Cost & cost
cost interface
std::vector< Edge * > changedEdges
newly changed edges
Vertex * start
start state
Vertex * goal
goal state
Vertex * last
last state
double km
km variable
fibheap_t openList
fibonacci heap
double eps
epsilon for cost comparision
Friends
class Graph
Constructor & Destructor Documentation
Search::Search (Graph & graph, const Cost & cost)
Initialize dsl with a graph and a cost interface
Parameters:
graph graph (the method will modify the nodes in the graph by changing certain search-related parameters stored at the nodes, the data or the original edge costs would not be changed)
cost cost interface
References openList.
Search::~Search () [virtual]
References changedEdges, and openList.
Member Function Documentation
double * Search::CalculateExtKey (double * key, Vertex & v) [protected]
References cost, DSL_MIN, dsl::Vertex::g, dsl::Cost::Heur(), INF, km, dsl::Vertex::rhs, and start.
Referenced by CalculateKey(), Insert(), and Update().
double * Search::CalculateKey (Vertex & v) [protected]
References CalculateExtKey(), and dsl::Vertex::key.
Referenced by ComputeShortestPath().
void Search::ChangeCost (Edge & e, double cost)
Change the cost of edge e
Parameters:
e edge
cost new cost
References changedEdges, dsl::Edge::cost, cost, dsl::Edge::costChange, and Eq().
Referenced by dsl::Graph::AddEdge(), dsl::GridSearch::SetCost(), and dsl::GridSearch3D::SetCost().
void Search::ComputeShortestPath () [protected]
References CalculateKey(), dsl::Edge::cost, DSL_MIN, Eq(), fibkey_compare(), dsl::Edge::from, dsl::Vertex::g, goal, graph, dsl::Vertex::in, INF, dsl::Vertex::key, MinSucc(), openList, Remove(), dsl::Vertex::rhs, dsl::Graph::search, start, Top(), TopKey(), Update(), and UpdateVertex().
Referenced by Plan().
bool dsl::Search::Eq (double a, double b) const [inline, protected]
Compare two doubles for equality
Parameters:
a first number
b second number
Returns:
References eps.
Referenced by ChangeCost(), ComputeShortestPath(), Plan(), dsl::Graph::RemoveEdge(), dsl::GridSearch::SetCost(), and dsl::GridSearch3D::SetCost().
void Search::Insert (Vertex & v) [protected]
References CalculateExtKey(), InsertExt(), and dsl::Vertex::key.
Referenced by UpdateVertex().
void Search::InsertExt (Vertex & v, double * key) [protected]
References dsl::Vertex::OPEN, openList, dsl::Vertex::openListNode, start, and dsl::Vertex::t.
Referenced by Insert(), and SetGoal().
Vertex * Search::MinSucc (double * minRhs, const Vertex & v) [protected]
References dsl::Edge::cost, cost, dsl::Vertex::g, goal, INF, dsl::Vertex::out, dsl::Cost::Real(), and dsl::Edge::to.
Referenced by ComputeShortestPath(), Plan(), and dsl::Graph::RemoveEdge().
int Search::Plan ()
Plan an initial path from start to goal, or if any cost changes are detected since it was last called (any calls to ChangeCost()) then it replans. The generated path can be obtained by following the next pointers from start vertex until goal vertex is reached
Returns:
total number of vertices along the path
References changedEdges, ComputeShortestPath(), dsl::Edge::cost, cost, dsl::Edge::costChange, DSL_MIN, Eq(), dsl::Edge::from, dsl::Vertex::g, goal, dsl::Cost::Heur(), dsl::Vertex::in, km, last, MinSucc(), dsl::Vertex::next, dsl::Vertex::out, dsl::Vertex::prev, dsl::Vertex::rhs, start, dsl::Edge::to, and UpdateVertex().
Referenced by dsl::GridSearch::Plan(), and dsl::GridSearch3D::Plan().
Vertex * Search::Pop () [protected]
void Search::Remove (Vertex & v) [protected]
References dsl::Vertex::CLOSED, openList, dsl::Vertex::openListNode, and dsl::Vertex::t.
Referenced by ComputeShortestPath(), dsl::Graph::RemoveVertex(), and UpdateVertex().
void Search::Reset ()
Reset the planner to its initial state this can be used for example if the goal state was changed but the graph structure is the same This is usually called internally at init and with every SetGoal()
References graph, km, last, openList, and dsl::Graph::vertices.
Referenced by SetGoal().
void dsl::Search::SetEps (double eps) [inline]
Set epsilon: this is used to compare cell costs
Parameters:
eps precision (1e-10 by default)
References eps.
void Search::SetGoal (const Vertex & v)
Set goal state this also resets the planner
Parameters:
v goal vertex
References cost, goal, dsl::Cost::Heur(), InsertExt(), dsl::Vertex::key, Reset(), dsl::Vertex::rhs, and start.
void Search::SetStart (const Vertex & v)
Set start state
Parameters:
v start vertex
References start.
Vertex * Search::Top () [protected]
References openList, start, and Update().
Referenced by ComputeShortestPath(), and TopKey().
double * Search::TopKey () [protected]
References dsl::Vertex::key, and Top().
Referenced by ComputeShortestPath().
void Search::Update (Vertex & v) [protected]
References CalculateExtKey(), fibkey_compare(), dsl::Vertex::key, dsl::Vertex::OPEN, openList, dsl::Vertex::openListNode, start, and dsl::Vertex::t.
Referenced by ComputeShortestPath(), Top(), and UpdateVertex().
void Search::UpdateVertex (Vertex & u) [protected]
References dsl::Vertex::g, Insert(), dsl::Vertex::OPEN, Remove(), dsl::Vertex::rhs, dsl::Vertex::t, and Update().
Referenced by ComputeShortestPath(), Plan(), and dsl::Graph::RemoveEdge().
Friends And Related Function Documentation
friend class Graph [friend]
Member Data Documentation
std::vector<Edge*> dsl::Search::changedEdges [protected]
newly changed edges
Referenced by ChangeCost(), Plan(), and ~Search().
const Cost& dsl::Search::cost [protected]
cost interface
Reimplemented in dsl::GridSearch3D, and dsl::GridSearch.
Referenced by CalculateExtKey(), ChangeCost(), MinSucc(), Plan(), and SetGoal().
double dsl::Search::eps [protected]
epsilon for cost comparision
Referenced by Eq(), and SetEps().
Vertex* dsl::Search::goal [protected]
goal state
Referenced by ComputeShortestPath(), MinSucc(), Plan(), dsl::Graph::RemoveEdge(), and SetGoal().
Graph& dsl::Search::graph [protected]
graph
Reimplemented in dsl::GridSearch3D, and dsl::GridSearch.
Referenced by ComputeShortestPath(), and Reset().
double dsl::Search::km [protected]
km variable
Referenced by CalculateExtKey(), Plan(), and Reset().
Vertex* dsl::Search::last [protected]
last state
Referenced by dsl::Graph::AddEdge(), Plan(), dsl::Graph::RemoveEdge(), dsl::Graph::RemoveVertex(), and Reset().
fibheap_t dsl::Search::openList [protected]
fibonacci heap
Referenced by ComputeShortestPath(), InsertExt(), Remove(), Reset(), Search(), Top(), Update(), and ~Search().
Vertex* dsl::Search::start [protected]
start state
Referenced by CalculateExtKey(), ComputeShortestPath(), InsertExt(), dsl::GridSearch::Plan(), Plan(), dsl::GridSearch3D::Plan(), SetGoal(), SetStart(), Top(), and Update().
The documentation for this class was generated from the following files:
/home/matt/dsl/lib/search.h
/home/matt/dsl/lib/search.cc