D*Lite: Spline< X, Y > Class Template Reference
Spline< X, Y > Class Template Reference
#include <spline.h>
Classes
class Element
Public Member Functions
Spline ()
Spline (const std::vector< X > &x, const std::vector< Y > &y)
virtual ~Spline ()
Y operator[] (const X &x) const
Y interpolate (const X &x) const
std::vector< Y > operator[] (const std::vector< X > &xx) const
std::vector< Y > interpolate (const std::vector< X > &xx) const
Protected Types
typedef Element element_type
Protected Attributes
std::vector< element_type > mElements
Detailed Description
template<typename X, typename Y>
class Spline< X, Y >
Templated on type of X, Y. X and Y must have operator +, -, *, /. Y must have defined a constructor that takes a scalar.
Member Typedef Documentation
template<typename X, typename Y> typedef Element Spline< X, Y >::element_type [protected]
Constructor & Destructor Documentation
template<typename X, typename Y> Spline< X, Y >::Spline () [inline]
An empty, invalid spline
template<typename X, typename Y> Spline< X, Y >::Spline (const std::vector< X > & x, const std::vector< Y > & y) [inline]
A spline with x and y values
References Spline< X, Y >::mElements.
template<typename X, typename Y> virtual Spline< X, Y >::~Spline () [inline, virtual]
Member Function Documentation
template<typename X, typename Y> Y Spline< X, Y >::interpolate (const X & x) const [inline]
References Spline< X, Y >::mElements.
Referenced by Spline< X, Y >::operator[]().
template<typename X, typename Y> std::vector<Y> Spline< X, Y >::interpolate (const std::vector< X > & xx) const [inline]
References Spline< X, Y >::mElements.
template<typename X, typename Y> Y Spline< X, Y >::operator[] (const X & x) const [inline]
References Spline< X, Y >::interpolate().
template<typename X, typename Y> std::vector<Y> Spline< X, Y >::operator[] (const std::vector< X > & xx) const [inline]
References Spline< X, Y >::interpolate().
Member Data Documentation
template<typename X, typename Y> std::vector<element_type> Spline< X, Y >::mElements [protected]
Referenced by Spline< X, Y >::interpolate(), and Spline< X, Y >::Spline().
The documentation for this class was generated from the following file:
/home/matt/dsl/lib/spline.h