D*Lite: dsl::TravSearch Class Reference
dsl::TravSearch Class Reference
#include <travsearch.h>
Public Member Functions
TravSearch (int width, int height, const double *map=0, double scale=1.0)
virtual double CalcEdgeCost (double v1cost, double v2cost, double elength)
Constructor & Destructor Documentation
TravSearch::TravSearch (int width, int height, const double * map = 0, double scale = 1.0)
The planner allocates all states in the beginning a valid map of size width*height should be provided scale is used to multiply each cell value and each neighbor transition value before they are used for planning
Parameters:
width width
height height
map a double array of size width*height containing occupancy info (optional)
scale the size of each cell (default is 1.0)
References dsl::Graph::AddEdge(), CalcEdgeCost(), dsl::GridSearch::graph, dsl::GridSearch::height, dsl::GridSearch::NBR_COSTS_, NBR_COUNT, dsl::GridSearch::NBR_OFFSETS, dsl::GridSearch::vertexMap, and dsl::GridSearch::width.
Member Function Documentation
double TravSearch::CalcEdgeCost (double v1cost, double v2cost, double elength) [virtual]
Calculates the cost (usually a height) gradient between two vertices. param v1cost cost of "from" vertex param v2cost cost of "to" vertex param ecost cost of edge
Reimplemented from dsl::GridSearch.
References dsl::GridSearch::scale.
Referenced by TravSearch().
The documentation for this class was generated from the following files:
/home/matt/dsl/lib/travsearch.h
/home/matt/dsl/lib/travsearch.cc