D*Lite: dsl::Graph Class Reference
dsl::Graph Class Reference
#include <graph.h>
Public Member Functions
Graph ()
virtual ~Graph ()
void AddVertex (Vertex &v)
void RemoveVertex (Vertex &v, bool re=true, bool del=false)
void AddEdge (Edge &e)
void RemoveEdge (Edge &e, bool update=true, bool del=false)
bool Exists (const Vertex &v) const
Public Attributes
std::map< int, Edge * > edges
all edges
std::map< int, Vertex * > vertices
all vertices
Protected Attributes
Search * search
search operating on this graph
Friends
class Search
Detailed Description
Generic graph data structure using hashtables for storing vertices and edges for quick add/remove ops
Author: Marin Kobilarov -- Copyright (C) 2004
Constructor & Destructor Documentation
Graph::Graph ()
Initialize an empty graph
Graph::~Graph () [virtual]
Member Function Documentation
void Graph::AddEdge (Edge & e)
Add edge. If the from/to vertices of the edge are set then they are modified to incude this edge in their outgoing/incoming respectively list of edges
Parameters:
e edge
References dsl::Search::ChangeCost(), dsl::Edge::cost, edges, dsl::Edge::from, dsl::Edge::id, dsl::Vertex::in, INF, dsl::Search::last, dsl::Vertex::out, search, and dsl::Edge::to.
Referenced by dsl::GridSearch::AddEdge(), dsl::GridSearch3D::AddEdge(), dsl::GridSearch::GridSearch(), and dsl::GridSearch3D::GridSearch3D().
void Graph::AddVertex (Vertex & v)
Add vertex. Vertex is added to map of vertices. No other graph elements are modified.
Parameters:
v vertex
References dsl::Vertex::id, and vertices.
Referenced by dsl::GridSearch::GridSearch(), and dsl::GridSearch3D::GridSearch3D().
bool Graph::Exists (const Vertex & v) const
Checks if a vertex exists
Parameters:
v the vertex
Returns:
true if present in the graph
References dsl::Vertex::id, and vertices.
void Graph::RemoveEdge (Edge & e, bool update = true, bool del = false)
Remove edge. If the from/to vertices of the edge are set then they are modified to remove this edge in their outgoing/incoming respectively list of edges
Parameters:
e edge
update whether to update the graph/search data to reflect the influence of removing this edge if this is done during search. Normally, one can pass update=false only when cleaning up the graph upon deletion, for efficiency
del delete/free all removed data? (false by default, the idea is that we care more about speed rather than memory; and these will be deleted when the graph object is deleted anyways)
References dsl::Edge::cost, dsl::Edge::costChange, edges, dsl::Search::Eq(), dsl::Edge::from, dsl::Vertex::g, dsl::Search::goal, dsl::Edge::id, dsl::Vertex::in, INF, dsl::Search::last, dsl::Search::MinSucc(), dsl::Vertex::openListNode, dsl::Vertex::out, dsl::Vertex::rhs, search, dsl::Edge::to, and dsl::Search::UpdateVertex().
Referenced by RemoveVertex().
void Graph::RemoveVertex (Vertex & v, bool re = true, bool del = false)
Remove vertex v. Incoming and outgoing edges are removed by default but can be kept intact if paramter re is set ot false
Parameters:
v vertex
re remove edges? (true by default)
del delete/free all removed data? (false by default)
References dsl::Vertex::id, dsl::Vertex::in, dsl::Search::last, dsl::Vertex::out, dsl::Search::Remove(), RemoveEdge(), search, and vertices.
Referenced by dsl::GridSearch::RemoveVertex(), and dsl::GridSearch3D::RemoveVertex().
Friends And Related Function Documentation
friend class Search [friend]
Member Data Documentation
std::map<int, Edge*> dsl::Graph::edges
all edges
Referenced by AddEdge(), and RemoveEdge().
Search* dsl::Graph::search [protected]
search operating on this graph
Referenced by AddEdge(), dsl::Search::ComputeShortestPath(), RemoveEdge(), and RemoveVertex().
std::map<int, Vertex*> dsl::Graph::vertices
all vertices
Referenced by AddVertex(), Exists(), RemoveVertex(), and dsl::Search::Reset().
The documentation for this class was generated from the following files:
/home/matt/dsl/lib/graph.h
/home/matt/dsl/lib/graph.cc