D*Lite: dsl::GridSearch3D Class Reference
dsl::GridSearch3D Class Reference
#include <gridsearch3d.h>
Public Member Functions
GridSearch3D (int length, int width, int height, const double *map=0, double scale=1.0)
virtual ~GridSearch3D ()
void SetCost (int x, int y, int z, double cost)
double GetCost (int x, int y, int z) const
void SetMap (const double *map)
void SetStart (int x, int y, int z)
void SetGoal (int x, int y, int z)
void Plan (GridPath3D &path)
void OptPath (const GridPath3D &path, GridPath3D &optPath) const
void SmoothPathBezier (const GridPath3D &path, GridPath3D &smoothPath, double smoothness) const
void SmoothPathSpline (const GridPath3D &path, GridPath3DPlusTime &smoothPath, double v, double timeStep) const
void SmoothPathOptCost (const GridPath3D &path, GridPath3DPlusTime &smoothPath, double v, double timeStep) const
Vertex * GetVertex (int x, int y, int z) const
void RemoveVertex (int x, int y, int z)
void AddEdge (int x1, int y1, int z1, int x2, int y2, int z2)
Public Attributes
int length
length of cost grid
int width
width of cost grid
int height
height of cost grid
double scale
scale of each cell cost and each transition cost
double * map
cost grid array of size width*height
Protected Attributes
Graph graph
graph
GridCost3D cost
cost interface
Vertex ** vertexMap
vertex grid array of size width*height
Constructor & Destructor Documentation
GridSearch3D::GridSearch3D (int length, int width, int height, const double * map = 0, double scale = 1.0)
The planner allocates all states in the beginning a valid map of size length*width*height should be provided scale is used to multiply each cell value and each neighbor transition value before they are used for planning
Parameters:
length length
width width
height height
map a double array of size length*width*height containing occupancy info (optional)
scale the size of each cell (default is 1.0)
References dsl::Graph::AddEdge(), dsl::Graph::AddVertex(), graph, height, length, MAX, NBR_COUNT, vertexMap, and width.
GridSearch3D::~GridSearch3D () [virtual]
References dsl::Vertex::data, height, length, map, vertexMap, and width.
Member Function Documentation
void GridSearch3D::AddEdge (int x1, int y1, int z1, int x2, int y2, int z2)
Useful method for adding edges b/n vertices
Parameters:
x1 from x-coordiante
y1 from y-coordiante
z1 from z-coordiante
x2 to x-coordiante
y2 to y-coordiante
z2 to z-coordiante
References dsl::Graph::AddEdge(), GetCost(), GetVertex(), graph, MAX, and scale.
double GridSearch3D::GetCost (int x, int y, int z) const
Get the cost of an individual cell
Parameters:
x x
y y
z z
Returns:
cost
References DSL3D_OCCUPIED, height, length, map, and width.
Referenced by AddEdge(), SetCost(), and SmoothPathOptCost().
Vertex * GridSearch3D::GetVertex (int x, int y, int z) const
Useful method to get the graph vertex at position (x,y)
Parameters:
x x-coordinate
y y-coordinate
z z-coordinate
Returns:
corresponding vertex or 0 if none there
References height, length, vertexMap, and width.
Referenced by AddEdge(), RemoveVertex(), SetGoal(), and SetStart().
void GridSearch3D::OptPath (const GridPath3D & path, GridPath3D & optPath) const
Optimize the path produced by Plan
Parameters:
path an initial obstacle-free path (e.g. one produced by calling Plan(path))
optPath a new path resulting from optimizing the original path path (i.e. a producing a shorter path with minimal number of obstacle-free segments)
References dsl::GridPath3D::count, DSL3D_OCCUPIED, dsl::GridPath3D::len, length, map, dsl::GridPath3D::pos, RAY_TRACE_STEP, and width.
void GridSearch3D::Plan (GridPath3D & path)
Compute path b/n start and goal vertices these vertices should be already set
Parameters:
path the resulting path
References dsl::GridPath3D::count, dsl::Vertex::data, dsl::GridPath3D::len, dsl::Vertex::next, dsl::Search::Plan(), dsl::GridPath3D::pos, and dsl::Search::start.
void GridSearch3D::RemoveVertex (int x, int y, int z)
Useful method to remove a vertex at (x,y)
Parameters:
x x-coordinate
y y-coordinate
z z-coordinate
References GetVertex(), graph, and dsl::Graph::RemoveVertex().
void GridSearch3D::SetCost (int x, int y, int z, double cost)
Change the cost of an individual cell
Parameters:
x x-coordinate
y y-coordinate
z z-coordinate
cost cost
References dsl::Search::ChangeCost(), cost, dsl::Search::Eq(), GetCost(), dsl::Vertex::in, length, map, MAX, dsl::Vertex::out, scale, vertexMap, and width.
Referenced by SetMap().
void GridSearch3D::SetGoal (int x, int y, int z)
Set goal location in the map
Parameters:
x x-coord
y y-coord
z z-coord
References GetVertex().
void GridSearch3D::SetMap (const double * map)
Change the costs of all cells at once
Parameters:
map a length*width*height double array containing occupancy data
References height, length, SetCost(), and width.
void GridSearch3D::SetStart (int x, int y, int z)
Set start location in the map
Parameters:
x x-coord
y y-coord
z z-coord
References GetVertex().
void GridSearch3D::SmoothPathBezier (const GridPath3D & path, GridPath3D & smoothPath, double smoothness) const
Smooth the path produced by Plan with a Bezier interpolation
Parameters:
path an initial obstacle-free path (e.g. one produced by calling Plan(path))
optPath a new path resulting from smoothing the original path path
smoothness smoothness of the curve
References dsl::GridPath3D::count, dsl::GridPath3D::len, dsl::GridPath3D::pos, and RAY_TRACE_STEP.
void GridSearch3D::SmoothPathOptCost (const GridPath3D & path, GridPath3DPlusTime & smoothPath, double v, double timeStep) const
Smooth the path produced by Plan with a clamped cubic spline, choosing the control points in order to minimize a cost function
Parameters:
path an initial obstacle-free path (e.g. one produced by calling Plan(path))
optPath a new path resulting from smoothing the original path path
v the average velocity along the path
timeStep the time between each point along the generated path
References dsl::GridPath3D::count, DSL3D_OCCUPIED, GetCost(), dsl::GridPath3D::len, dsl::GridPath3D::pos, SmoothPathSpline(), and dsl::GridPath3DPlusTime::times.
void GridSearch3D::SmoothPathSpline (const GridPath3D & path, GridPath3DPlusTime & smoothPath, double v, double timeStep) const
Smooth the path produced by Plan with a clamped cubic spline
Parameters:
path an initial obstacle-free path (e.g. one produced by calling Plan(path))
optPath a new path resulting from smoothing the original path path
v the average velocity along the path
timeStep the time between each point along the generated path
References dsl::GridPath3D::count, dsl::GridPath3D::len, dsl::GridPath3D::pos, and dsl::GridPath3DPlusTime::times.
Referenced by SmoothPathOptCost().
Member Data Documentation
GridCost3D dsl::GridSearch3D::cost [protected]
cost interface
Reimplemented from dsl::Search.
Referenced by SetCost().
Graph dsl::GridSearch3D::graph [protected]
graph
Reimplemented from dsl::Search.
Referenced by AddEdge(), GridSearch3D(), and RemoveVertex().
int dsl::GridSearch3D::height
height of cost grid
Referenced by GetCost(), GetVertex(), GridSearch3D(), SetMap(), and ~GridSearch3D().
int dsl::GridSearch3D::length
length of cost grid
Referenced by GetCost(), GetVertex(), GridSearch3D(), OptPath(), SetCost(), SetMap(), and ~GridSearch3D().
double* dsl::GridSearch3D::map
cost grid array of size width*height
Referenced by GetCost(), OptPath(), SetCost(), and ~GridSearch3D().
double dsl::GridSearch3D::scale
scale of each cell cost and each transition cost
Referenced by AddEdge(), and SetCost().
Vertex** dsl::GridSearch3D::vertexMap [protected]
vertex grid array of size width*height
Referenced by GetVertex(), GridSearch3D(), SetCost(), and ~GridSearch3D().
int dsl::GridSearch3D::width
width of cost grid
Referenced by GetCost(), GetVertex(), GridSearch3D(), OptPath(), SetCost(), SetMap(), and ~GridSearch3D().
The documentation for this class was generated from the following files:
/home/matt/dsl/lib/gridsearch3d.h
/home/matt/dsl/lib/gridsearch3d.cc