D*Lite: /home/matt/dsl/bin/test.cc File Reference
test.cc File Reference
#include <stdio.h>
#include <assert.h>
#include <math.h>
#include <sys/time.h>
#include <stdlib.h>
#include <string.h>
#include "gridsearch.h"
#include "distedgecost.h"
Functions
void save_map (const char *map, int width, int height, const char *filename)
char * load_map (int *width, int *height, const char *filename)
void timer_start (struct timeval *time)
long timer_us (struct timeval *time)
int main (int argc, char **argv)
Function Documentation
char* load_map (int * width, int * height, const char * filename)
Referenced by main().
int main (int argc, char ** argv)
References dsl::GridPath::count, dsl::GridPath::len, load_map(), dsl::GridSearch::OptPath(), dsl::GridSearch::Plan(), dsl::GridPath::pos, dsl::GridSearch::RemoveVertex(), save_map(), dsl::GridSearch::SetCost(), dsl::GridSearch::SetGoal(), dsl::GridSearch::SetStart(), timer_start(), and timer_us().
void save_map (const char * map, int width, int height, const char * filename)
Referenced by main().
void timer_start (struct timeval * time)
Referenced by main().
long timer_us (struct timeval * time)
Referenced by main().